# -*- coding: utf-8 -*-
"""Measure where each frame looks and emit a degree -> frame lookup table.

Rebuild after replacing the portrait clip:

    ffmpeg -i public/portrait.mp4 -vf "scale=128:96,tile=16x15" -frames:v 1 \
           public/portrait-atlas.webp
    ffmpeg -i public/portrait.mp4 -vf "crop=340:52:150:98,scale=68:16,format=gray" \
           -f rawvideo eyes.raw
    python scripts/build-gaze-table.py eyes.raw > src/gaze-table.js

Design notes, both learned the hard way:

* Track the IRIS, not the head silhouette. The brief asked for subtle head
  movement, which leaves the head centroid barely displaced and buried in
  noise; the irises travel three times as far and point the same way.
* Do not assume the sweep is a clean revolution. This clip wanders, stalls
  and returns to centre partway through, so fitting a monotonic circle and
  inverting it pairs neighbouring angles with unrelated poses. Picking the
  closest measured direction per degree assumes nothing about the path.
"""
import io
import math
import sys

W, H, N = 68, 16, 240
IRIS_LO, IRIS_HI = 0.08, 0.34
COMMIT = 12.0  # degrees of slack traded for a fully committed gaze

raw_path = sys.argv[1] if len(sys.argv) > 1 else "eyes.raw"
b = io.open(raw_path, "rb").read()
assert len(b) >= W * H * N, "unexpected raw size: %d" % len(b)

cents = []
for f in range(N):
    off = f * W * H
    sx = sy = sw = 0.0
    for y in range(H):
        for x in range(W):
            v = b[off + y * W + x] / 255.0
            if IRIS_LO < v < IRIS_HI:
                w = IRIS_HI - v
                sx += x * w
                sy += y * w
                sw += w
    cents.append((sx / sw, sy / sw) if sw else (W / 2.0, H / 2.0))

mx = sum(c[0] for c in cents) / N
my = sum(c[1] for c in cents) / N

samples = []
for x, y in cents:
    dx, dy = x - mx, y - my
    samples.append((
        (math.degrees(math.atan2(dy, dx)) + 360) % 360,
        math.hypot(dx, dy),
    ))

peak = max(s for _, s in samples) or 1.0
neutral = min(range(N), key=lambda f: samples[f][1])

table = []
for want in range(360):
    best, best_score = neutral, 1e9
    for f, (deg, strength) in enumerate(samples):
        off = abs((deg - want + 180) % 360 - 180)
        score = off - (strength / peak) * COMMIT
        if score < best_score:
            best_score, best = score, f
    table.append(best)

out = [
    "// Generated by scripts/build-gaze-table.py from the portrait clip.",
    "// Index is the cursor angle in degrees (0 = right, 90 = down);",
    "// the value is the atlas frame whose gaze points that way.",
    "export const GAZE_NEUTRAL = %d;" % neutral,
    "export const GAZE_FRAMES = %d;" % N,
    "export const GAZE_BY_DEGREE = [",
]
for i in range(0, 360, 20):
    out.append("  " + ", ".join("%3d" % v for v in table[i:i + 20]) + ",")
out.append("];")
print("\n".join(out))

err = [abs((samples[table[w]][0] - w + 180) % 360 - 180) for w in range(360)]
sys.stderr.write("neutral frame %d\n" % neutral)
sys.stderr.write("heading error: mean %.1f deg, worst %.1f deg\n" % (sum(err) / 360, max(err)))
sys.stderr.write("distinct frames used: %d\n" % len(set(table)))
for want in (0, 45, 90, 135, 180, 225, 270, 315):
    sys.stderr.write("  %3d deg -> frame %3d (points %3.0f deg)\n"
                     % (want, table[want], samples[table[want]][0]))
